Feature/hide indicators
bigthinks/weathervane pull request #9
Opened 2017-02-03 01:01 UTC by tet3

Started messing around just trying to add functionality for #5 but got carried away and added the SLDS icon option. Though I think a new namespaced pull of SLDS is required to get some newer icons - there are several new ones in the Standard set, and Custom 101-113 are also not in the current static resource.

I addressed a couple of cases with #6 (added the PL values, and explicitly cast to String with valueOf() and then to Decimal. It would be great to handle dates, though.

2017-02-03 01:15 UTC, tet3 commented on src/classes/Indicators_Service.cls
> +/*				if (Cache.Org.contains('indicatorbar.partition1.spriteSet')) {
I thought Platform Cache would be a cool way to make the list of icon names be a little quicker, but a) I had to request it in my dev org, and b) the managed package Platfom Cache scenario is sub-optimal for OSS projects anyway. From https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_cache_partition_setup.htm: 
> If you’re working with managed packages, we recommend using Branch Packaging Orgs to share a namespace across partitions. This feature lets you maintain multiple orgs or partitions as “branches” of your primary org. For information about Branch Packaging Orgs, contact Salesforce.

2017-02-03 06:36 UTC, cdcarter requested changes
thomas - I will take a look  at this in an org tomorrow but on first glance it looks good, a few comments in this review.

though..., making a callout just for runtime validation of the sprite name seems like a bad idea (especially when we're doing things like casting through string and decimal adhoc.) since we're bundling a specific slds resource, you can simply inline the list in the class as a final constant instead.

2017-02-03 06:36 UTC, cdcarter commented on src/classes/Indicators_Service.cls
> +					return idNames;
you'd need to assign the value to the spriteSet member for it to actually be memoized.

2017-02-03 06:36 UTC, cdcarter commented on cumulusci.yml
> +        namespace: indicatorbar
include an explicit api version here - since the valueset name change in the .object is breaking-y

2017-02-09 20:50 UTC, tet3 commented on cumulusci.yml
> +        namespace: indicatorbar
@cdcarter 38.0 is ok, right? It's 39.0 that you're wanting to avoid?

2017-02-10 00:09 UTC, cdcarter commented on cumulusci.yml
> +        namespace: indicatorbar
yep!

2017-02-10 17:28 UTC, cdcarter approved these changes
Looks awesome!

2017-02-10 17:29 UTC, merged